/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Endpoint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EndpointServerless) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EndpointService) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EndpointServiceDataFederationOnlineArchive) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EndpointServiceServerless) Hub() {}
