apiVersion: cloud.mongodbatlas.crossplane.io/v1alpha1
kind: BackupSnapshot
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/backupsnapshot
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusterNameSelector:
      matchLabels:
        testing.upbound.io/example-name: my_cluster
    description: myDescription
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: my_cluster
    retentionInDays: 1

---

apiVersion: cloud.mongodbatlas.crossplane.io/v1alpha1
kind: BackupSnapshotRestoreJob
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/backupsnapshot
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusterName: MyCluster
    deliveryTypeConfig:
    - download: true
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    snapshotId: ${mongodbatlas_cloud_backup_snapshot.test.snapshot_id}

---

apiVersion: mongodbatlas.crossplane.io/v1alpha2
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/backupsnapshot
  labels:
    testing.upbound.io/example-name: my_cluster
  name: my-cluster
spec:
  forProvider:
    cloudBackup: true
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    providerInstanceSizeName: M10
    providerName: AWS
    providerRegionName: EU_WEST_2
