apiVersion: mongodbatlas.crossplane.io/v1alpha2
kind: AdvancedCluster
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1alpha2/advancedcluster
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusterType: REPLICASET
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    replicationSpecs:
    - regionConfigs:
      - analyticsSpecs:
        - instanceSize: M10
          nodeCount: 1
        electableSpecs:
        - instanceSize: M10
          nodeCount: 3
        priority: 7
        providerName: AWS
        regionName: US_EAST_1
