apiVersion: privatelink.mongodbatlas.crossplane.io/v1alpha1
kind: EndpointServerless
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/endpointserverless
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    providerName: AWS
